version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
    time: "10:00"
    timezone: "Asia/Kolkata"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  commit-message:
    prefix: "[Dependency] "
    prefix-development: "[DevDependency]
