[[headers]]
  for = "*.js"  # for caching js files
  [headers.values]
    Cache-Control = "public, max-age=7884000" # 3 months cache
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=7884000"
[[headers]]
  for = "*.png" # png files too
  [headers.values]
    Cache-Control = "public, max-age=7884000"