name: Doc2Pen	
on:	
  push:	
    branches: master 	
  pull_request:	
    branches: master	

jobs:	
  build:	

    runs-on: ubuntu-latest	

    steps:	
    - uses: actions/checkout@v2	

    - name: Deploy react app to github pages	
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1	
